#cloud-init

# create ssh passwordless user
users:
  - name: ubuntu
    home: /home/ubuntu
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDCxf7u+NgOBqsJPuD+XH7LiNtnwNkqIl2qfcgo1R6m5zvgnHwLnb6FX0x8HO+d4GSYOCad3qaAcULocxtGIlyUy1/qVLX9MAkgjPDchRAc7z+GcSgMenNr3BU1v3zgxSCOkHX1k4fUpvSceQVP/wTHOQYROIgGsOja1xLZwwk6VGgrcB2QH4+ndKHCN14A9bE4cbo0WWv6SVCLne98O+F7IIx0J6u7KRmbSKhRuJfe8d09r2I+0pUXaOM8bZiSoZ3FGbLyLhtG+tg2DFWOVHp0UaqaUqOTS5ip7gCQfPrjHQDvAX7eqYxxabqhJwQ/xH8nfMJRCTh/mcswUJGOlsGKf9wNRxrV9AjuTnkljBJHOleiMdXMqDepibYiKKEr1Z0yi0DcZ8l+uUyPWvP9JmMyjs6Cc/+L1rXTgIEaqUosoXhRBAAu9BA7deQbfBQxSonKGgNWMx+OQKBwnfN6ckymnD4GMk8q1d0DBO/aylK4YRmAFpSexDPPPYuNmrwZ0dHf6+LQfzqNXyy/nFSCTYo9DNLcMhZdbyZoO7OAHIP/cOWtBscH/k61pafG7APVmnDyqW6uK9//3Sg22t6X4Yy7xVAOjMfmtJInSSSU2iuUzhGe4GvmZt2dnyXt4y/Muqlq77nJfWdC9Agnp69fIkAjP0xMnd+KVSVgKl0SoY2aMQ==

bootcmd:
  - sudo swapoff -a

# create files
write_files:
  - path: /etc/systemd/resolved.conf
    append: true
    content: |
      MulticastDNS=yes

  - path: /etc/systemd/system/mdns@.service
    content: |
      [Service]
      Type=oneshot
      ExecStart=/usr/bin/systemd-resolve --set-mdns=yes --interface=%i
      After=sys-subsystem-net-devices-%i.device

      [Install]
      WantedBy=sys-subsystem-net-devices-%i.device

  - path: /etc/modules-load.d/containerd.conf
    content: |
      overlay
      br_netfilter

  - path: /etc/sysctl.d/99-kubernetes-cri.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
      net.bridge.bridge-nf-call-ip6tables = 1

  - path: /etc/crictl.yaml
    content: |
      runtime-endpoint: unix:///run/containerd/containerd.sock
      image-endpoint: unix:///run/containerd/containerd.sock
      timeout: 10
      debug: true

  - path: /etc/default/kubelet 
    content: |
      KUBELET_EXTRA_ARGS=--container-runtime=remote --container-runtime-endpoint='unix:///run/containerd/containerd.sock'
                                                
  - path: /etc/containerd/config.toml
    content: |
      version = 2

      [plugins]
        [plugins."io.containerd.grpc.v1.cri"]
          [plugins."io.containerd.grpc.v1.cri".containerd]
            snapshotter = "overlayfs"
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
              [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
                runtime_type = "io.containerd.runc.v2"
                [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
                  SystemdCgroup = true

runcmd:
  - sudo sysctl --system
  - sudo systemctl restart systemd-resolved.service
  - sudo systemctl start mdns@enp0s2.service
  - sudo systemctl enable mdns@enp0s2.service
  - sudo modprobe overlay
  - sudo modprobe br_netfilter

package_upgrade: true
package_reboot_if_required: true