#cloud-init

# create ssh passwordless user
users:
  - name: ubuntu
    groups: docker
    home: /home/ubuntu
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC9OQi8RVX2cLAQTlpAJwZdKQEALSmFc/0OI+KuDzNiFef42bLyyun0aEGO/EeEqpqZqD+TUfhzvu9h6XtWBOQGnEiDysSKrS3X3ggNdn3+hd0EBkdFqFw0BUhLio+S31kMI9XSukbZERmhY1tmv9w5zC3TTnDVUY5FHnepag2qgH4omBDk7sn50giNYz9BlC6XdeZgF2M6jxhKX30km+IiHUppuZH0kpWvBicipUUVioB2BocgdpIK6FSs2NWcvmswlYLQH2XaIdu7aaqW9G+g/2ytu4R/IaSfGhNidsHhsBw9iYZI3uHa4ebvUne5JxGNaE7zSITOyDtGVi1QyEKPGbHx6JagWj736u03xTOE5PILSqonbmdf3sVdcdH5r1O6UUO3QERED/9DlQtKz2qmvpZbGpclmQLN3G3SlurGsUnXzz97CxFDER93Xgf0bMHpvUK3JESXr4SRqAxPn0mA6hcqTyxrIDegd8xnPk54KXa67IQ8sM9Xd/zAbo2WB/tfJIvpfiix+w2c2Y6IOCwKuPncIWXXnxeOGSg892JiFDMrYlhesmmb7/L2/YOnGUN+I7Zmu7pQUNVXgHhbzS87gG5TDIedsbbws3n6gbxQukBq8I9Amew7gVU44XyFA/7t2Hp2UbToQJSiKY/C2io6Uo2Plo/gXCoNMDc444DqJw==

# add apt source for kubernetes
apt:
  sources:
    kubernetes:
      source: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
      keyserver: keyserver.ubuntu.com
      keyid: 59FE0256827269DC81578F928B57C5C2836F4BEB

# install needed packages      
package_update: true
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent 
  - software-properties-common
  - docker.io
  - [kubeadm, 1.22.8-00]
  - [kubectl, 1.22.8-00]
  - [kubelet, 1.22.8-00]

# create the docker group
groups:
  - docker

# Add default auto created user to docker group
system_info:
  default_user:
    groups: [docker]

# create files
write_files:
  - path: /etc/systemd/resolved.conf
    append: true
    content: |
      MulticastDNS=yes

  - path: /etc/systemd/system/mdns@.service
    content: |
      [Service]
      Type=oneshot
      ExecStart=/usr/bin/systemd-resolve --set-mdns=yes --interface=%i
      After=sys-subsystem-net-devices-%i.device

      [Install]
      WantedBy=sys-subsystem-net-devices-%i.device

  - path: /etc/docker/daemon.json
    content: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2"
      }

  - path: /etc/sysconfig/kubelet 
    content: |
      KUBELET_EXTRA_ARGS=--cgroup-driver=systemd

runcmd:
  - sudo swapoff -a
  - systemctl restart systemd-resolved.service
  - systemctl start mdns@enp0s2.service
  - systemctl enable mdns@enp0s2.service

package_reboot_if_required: true