---
- hosts: control
  become: true
  tasks:
    - name: get join command for workers
      shell: kubeadm token create --print-join-command
      register: JOIN_COMMAND
      
- hosts: worker
  become: true
  tasks:
    - name: Configure workers
      include_tasks: join-workers-tasks.yaml