---
- name: Kubernetes upgrade
  hosts: control:worker
  become: true
  serial: 1
  tasks:
    - name: Upgrade nodes
      ansible.builtin.include_tasks: upgrade-node-tasks.yaml
      vars:
        upgrade_version: 1.34.1
