---
- name: update kubernetes version for worker nodes
  hosts: worker
  become: true
  tasks:
  - name: upgrade worker nodes
    include_tasks: upgrade-worker-tasks.yaml
    vars:
      upgrade_version: 1.23.6