configurations:
  - vmType: control
    nodeCount: 2
    spec: '-c 2 -m 3G -d 20G'
  - vmType: worker
    nodeCount: 3
    spec: '-c 2 -m 1500M -d 20G'
  - vmType: loadbalancer
    nodeCount: 1
    spec: '-c 1 -m 1G -d 5G'