---
- name: create Multipass VMs for a K8s cluster
  hosts: localhost
  tasks:
  - name: create ssh key directory
    become: false
    file:
      path: "/tmp"
      state: directory
    register: ssh_key_path

  - name: generate SHH key
    openssh_keypair:
      path: "{{ ssh_key_path.path }}/id_ssh_rsa"
      type: rsa
      size: 4096
      state: present
      force: no
      regenerate: never
    register: sshkey

  - name: read k8s cluster VM configuration from file
    include_vars:
      file: "{{ configFile }}"
      name: config

  - name: configure vm
    include_tasks: create-vm-tasks.yaml
    vars:
      clusterConfig: "{{ conf }}"
    loop: "{{ config.configurations }}"
    loop_control:
      loop_var: conf

  - name: refreshing inventory
    meta: refresh_inventory

- name: initialize nodes
  hosts: control:worker
  become: true
  tasks:
  - name: set KUBERNETES VERSION in kubeadm config template
    set_fact:
      KUBERNETES_VERSION: "1.25.0"

  - name: install packages
    include_tasks: install-packages-tasks.yaml

- name: configure loadbalancer for control plane nodes
  hosts: loadbalancer
  tasks:
    - name: configure lb
      include_tasks: ../loadbalancer/configure-lb-tasks.yaml

- name: initialize first control plane node
  hosts: control[0]
  become: true
  tasks:
    - name: Configure first control plane node
      block: 
        - name: check if node is part of cluster
          become: false
          shell: kubectl get nodes {{ inventory_hostname }}
          delegate_to: localhost
      rescue:
        - name: configure first control plane node since node is not part of cluster
          include_tasks: ../control/init-first-ctrl-node-tasks.yaml

- name: configure all other nodes
  hosts: control:worker
  serial: 1
  become: true
  tasks:
    - name: Configure remaining nodes
      block: 
        - name: Check if node is part of cluster
          become: false
          shell: kubectl get nodes {{ inventory_hostname }}
          delegate_to: localhost
      rescue:
        - name: Configure worker nodes if node isn't in the cluster
          include_tasks: join-cluster-tasks.yaml