---
- name: create Multipass VMs for a K8s cluster
  hosts: localhost
  tasks:
  - name: create ssh key directory
    become: false
    file:
      path: "/tmp"
      state: directory
    register: ssh_key_path

  - name: generate SHH key
    openssh_keypair:
      path: "{{ ssh_key_path.path }}/id_ssh_rsa"
      type: rsa
      size: 4096
      state: present
      force: no
    register: sshkey

  - name: read k8s cluster node VM configuration from file
    include_vars:
      file: "{{ configFile }}"
      name: config

  - name: configure nodes
    include_tasks: create-nodes-tasks.yaml
    vars:
      clusterConfig: "{{ conf }}"
    loop: "{{ config.configurations }}"
    loop_control:
      loop_var: conf

  - name: refreshing inventory
    meta: refresh_inventory

- import_playbook: ../loadbalancer/playbook.yaml
- import_playbook: ../control/playbook.yaml
- import_playbook: ../worker/playbook.yaml