#cloud-init

# create ssh passwordless user
users:
  - name: ubuntu
    home: /home/ubuntu
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDWxvrzbMsN1TJu68ePl+EiXuLh7th7ElH8M6pPICrCMUlCqGcbFVEhzBsn8UAuca3m9N+qGCyTWc0AC10DEPEWXju1WP+6Y8kpDT+JCVcr+z42vgL4p4+tTtfmS+foG1Dr7D2hIdgAyMRLQNRT7OGA9f8phwDxKooBd8xoefBha1BskTfPCxzzNjyjhM0quvwoC52zzyfuHU2MR77XqX3Seh8qbwtWgBy5u9eEhIN9xvP8QHAD3Ru4CSeqk2A12CjLYCxkR4SMXzerI7IPe6bMZ2eM9ca/g8rViXayz9VLbLNkUUuNSKz3kwHqMo6jDubF9Vm5pXlox7ACItnpTMe1cn5vuqyaQnHo6gQ5RfyMEEDrAzdmG+61WNxcUAPg+zEhkG+NJIjAuFb9p7DzRpz4hsYFDpLgfGph6le5pAQLTBxUpJWaTK9GkfFe4EdyOIr2CyYWljZTdXYYpdvPDYTeLxPvOiqQHJmt6s4GO6gZJhHydcl9ONWPz/QZmgsylhq8eTraZ7MVtwGKREmROy4K2YkkV29FiPkVZ8whrtSeYSPoGUvA+cngZayZyADaKTbau4eSv9I8b42atvZKbP8LFd9fOA53Ay+brkunWNAMB76bN+I1JFT4jqWbZp0yccpqZY9lRZ6KOV70GbrRuVlboWXB9zAk0h/NjkhlsGmvcw==

# install needed packages      
package_update: true
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - haproxy

# create files
write_files:
  - path: /etc/systemd/resolved.conf
    append: true
    content: |
      MulticastDNS=yes

  - path: /etc/systemd/system/mdns@.service
    content: |
      [Service]
      Type=oneshot
      ExecStart=/usr/bin/systemd-resolve --set-mdns=yes --interface=%i
      After=sys-subsystem-net-devices-%i.device

      [Install]
      WantedBy=sys-subsystem-net-devices-%i.device

runcmd:
  - sudo swapoff -a
  - systemctl restart systemd-resolved.service
  - systemctl start mdns@enp0s2.service
  - systemctl enable mdns@enp0s2.service

package_reboot_if_required: true