---
- name: check that the haproxy.cfg exists
  stat:
    path: ./haproxy/haproxy.cfg
  register: cfg_file

- name: create haproxy directory
  file:
    path: ./haproxy
    state: directory

- name: copy default haproxy.cfg file
  copy:
    src: /etc/haproxy/haproxy.cfg
    dest: ./haproxy/haproxy.cfg
    remote_src: true
  when: not cfg_file.stat.exists

- name: create haproxy config
  template:
    src: ./haproxy-cfg-template.j2
    dest: ./haproxy/k8s-haproxy.cfg

- name: assemble haproxy configs
  become: true
  assemble:
    src: ./haproxy/
    dest: /etc/haproxy/haproxy.cfg

# - name: Sleep for 60 seconds before starting haproxy
#   wait_for:
#     timeout: 60
#   delegate_to: localhost

- name: reload haproxy svc
  become: true
  systemd:
    name: haproxy
    state: restarted
    daemon_reload: true
