---
- name: Update kubernetes version for control nodes
  hosts: control
  become: true
  serial: 1
  tasks:
  - name: upgrade control nodes
    include_tasks: upgrade-control-tasks.yaml
    vars:
      upgrade_version: 1.23.6