---
- name: Install packages that allow apt to be used over HTTPS
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - cgroup-tools
      - python3-kubernetes

- name: Adding apt repository for Docker
  deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/ubuntu
    suites: '{{ ansible_distribution_release }}'
    components: stable
    architectures: arm64
    state: present
    enabled: yes
    signed_by: https://download.docker.com/linux/ubuntu/gpg

- name: Install containerd
  ansible.builtin.apt:
    name: containerd.io=1.7.27-1
    state: present
    update_cache: true

- name: Adding apt repository for Kubernetes
  deb822_repository:
    name: kubernetes
    types: deb
    uris: https://pkgs.k8s.io/core:/stable:/v1.32/deb/
    suites: [/]
    state: present
    enabled: yes
    architectures: arm64
    signed_by: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key

- name: Install Kubernetes binaries
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - kubelet={{ KUBERNETES_VERSION }}-1.1
      - kubeadm={{ KUBERNETES_VERSION }}-1.1
      - kubectl={{ KUBERNETES_VERSION }}-1.1

- name: Start containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    daemon_reload: true

- name: Start kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: restarted
    daemon_reload: true
