---
- name: join workers
  hosts: worker
  vars:
    join_command: "{{ hostvars[groups['master'][0]]['JOIN_COMMAND']['stdout'] }}"
  become: true
  tasks:
    - name: Configure workers
      include_tasks: join-workers-tasks.yaml