# kubeadm-config.yaml
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
certificateKey: 14604e2bf92807ee534a9b9e0cbf0da819717b9f5bafd32bf774da8f0562cd19
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: v1.22.8
networking:
  podSubnet: 10.244.0.0/16
apiServer:
  certSANs:
  - "192.168.64.210"
controlPlaneEndpoint: "192.168.64.224:6443"
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: "ipvs"
ipvs:
  strictARP: true