# kubeadm-config.yaml
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
certificateKey: 330395e53116de0885983e293b5fb621c9d912f8621f82db32d43595496bb5f5
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: v1.22.8
networking:
  podSubnet: 10.244.0.0/16
apiServer:
  certSANs:
  - "192.168.64.210"
controlPlaneEndpoint: "192.168.64.210:6443"
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: "ipvs"
ipvs:
  strictARP: true