---
- hosts: control
  become: true
  tasks:
    - name: install packages
      include_tasks: ../main/install-packages-tasks.yaml

- name: initialize first control plane node
  hosts: control
  become: true
  tasks:
    - name: Configure workers
      block: 
        - name: Check if node is part of cluster
          become: false
          shell: kubectl get nodes {{ inventory_hostname }}
          delegate_to: localhost
      rescue:
        - name: init first control plane node
          include_tasks: init-first-ctrl-node-tasks.yaml
          run_once: true
      run_once: true
      
- name: initialize additional control plane nodes
  hosts: control[1:]
  become: true
  tasks:
    - name: Configure workers
      block: 
        - name: Check if node is part of cluster
          become: false
          shell: kubectl get nodes {{ inventory_hostname }}
          delegate_to: localhost
      rescue:
        - name: Configure control nodes if node isn't in the cluster
          include_tasks: join-control-plane-tasks.yaml