---
- name: change CRI to containerd
  hosts: control:worker
  become: true
  serial: 1
  tasks:
  - name: configure containerd as CRI
    include_tasks: configure-containerd-tasks.yaml
  - pause:
      minutes: 1